server:
  port: 8080
  servlet:
    context-path: /auth

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/auth-service"
    username: root
    password: Nguyenleviz@311
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  signerKey: "eHr30nG1PQoaJ6JucIPuRKmxyyOcMPs3hHNDaiSrqXKZiC5HneVjmiMxw12EE8eH"
  valid-duration: 1000

app:
  services:
    user: "http://localhost:8000/user"

file:
  upload-dir: "D:/Document/haui/Java-nang-cao/xthreads-social-network/user-service/img"
