server:
  port: 8888

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=1
        - id: user_service
          uri: http://localhost:8000
          predicates:
            - Path=${app.api-prefix}/user/**
          filters:
            - StripPrefix=1
        - id: chat_service
          uri: http://localhost:5000
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=1
        - id: post_service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/user-post/**
          filters:
            - StripPrefix=1