server:
  port: 8001
  servlet:
    context-path: /connect

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/friend-service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true