server:
  port: 8001
  servlet:
    context-path: /connect

spring:
  # MySQL Database Configuration
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/friendship-service"
    username: root
    password: Nguyenleviz@311
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP

  # JPA Configuration for MySQL
  jpa:
    hibernate:
      ddl-auto: update   # Use 'create', 'update', 'validate' as per your needs
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # MongoDB Database Configuration
  data:
    mongodb:
      # Optional authentication for MongoDB if needed
#      authentication-database: root
      database: friendship_db
      uri: mongodb+srv://root:root@xthreadsdb.qchmf.mongodb.net/?retryWrites=true&w=majority&appName=xthreadsDB
