server:
  port: 8088
  servlet:
    context-path: /user-post

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/post-service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

app:
  services:
    auth: "http://localhost:8080/auth"

file:
  upload-dir: "D:/Document/haui/Java-nang-cao/xthreads-social-network/post-service/img"