server:
  port: 8080
  servlet:
    context-path: /post


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/post_service_data"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
