server:
  port: 8000
  servlet:
    context-path: /user

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/user-service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "eHr30nG1PQoaJ6JucIPuRKmxyyOcMPs3hHNDaiSrqXKZiC5HneVjmiMxw12EE8eH"
  valid-duration: 100
